my:
 greeting: Hello World
 list:
  values: One, Two, Three 

db:
 connection: "{connectionString: 'http://_____', userName: 'foo', password: 'pass'}"
 host: 127.0.0.1
 port: 1200

app:
 name: Greeting API
 description: Welcome to ${app.name}!

management.endpoints.web.exposure.include: "*"

spring.cloud.config.uri: http://localhost:8888

spring.application.name: spring-boot-config